name: GitHub Actions CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.13.1]
    container:
      image: node:${{ matrix.node }}-alpine
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: Run tests
        run: |
          CI=true yarn test
